site_name: Jmix AppCommons
repo_url: https://github.com/pbaris/jmix-app-commons
copyright: Panos Bariamis

validation:
  omitted_files: warn
  absolute_links: warn  # Or 'relative_to_docs' - new in MkDocs 1.6
  unrecognized_links: warn
  anchors: warn

theme:
  name: gitbook
  highlightjs: true
  locale: en
  user_color_mode_toggle: true
  color_mode: light
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s

plugins:
  - search:
      indexing: 'full'

  - kroki:
      ServerURL: !ENV [ KROKI_SERVER_URL, 'https://kroki.nmlabs.gr' ]
      EnableBpmn: true
      EnableMermaid: true
      FileTypes:
        - png
        - svg
      FileTypeOverrides:
        mermaid: png

markdown_extensions:
  - admonition
  - abbr
  - def_list
  - nl2br
  - toc:
      permalink: "#"
      baselevel: 2
      separator: "_"

nav:
  - Home: index.md
