jmix.ui.menu-config=gr/netmechanics/jmix/appcommons/menu.xml
jmix.core.available-locales=en,el
jmix.ui.view-file-extensions=htm, html, jpg, png, jpeg, pdf
jmix.ui.navigation.use-nanoseconds-in-url-params=false
jmix.eclipselink.use-inner-join-in-condition=true
jmix.ui.legacy-monitoring-enabled=true
jmix.ui.use-legacy-test-id=true
