name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install MkDocs and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs
          pip install mkdocs-shadcn
          pip install mkdocs-git-revision-date-localized-plugin 
          pip install mkdocs-plantuml
          pip install markdown-inline-graphviz
          pip install mkdocs-kroki-plugin
          pip install mkdocs-build-plantuml-plugin
          pip install mkdocs-git-committers-plugin-2
          pip install mkdocs-print-site-plugin

      - name: Build the documentation
        run: mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site