name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - 'mkdocs/**'
      - 'mkdocs.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs
          pip install mkdocs-material
          pip install mkdocs-git-authors-plugin
          pip install mkdocs-git-committers-plugin-2
          pip install mkdocs-git-revision-date-localized-plugin 
          pip install mkdocs-glightbox

      - name: Build the documentation
        run: mkdocs build --clean

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site